# Generated by Django 3.0.7 on 2022-10-07 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('agent_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AddEmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('Address', models.CharField(blank=True, max_length=150)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('employee_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=150)),
                ('start', models.DateField(blank=True, max_length=150)),
                ('end', models.DateField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField()),
                ('used_for_purpose', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='myformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('website_name', models.CharField(blank=True, max_length=150)),
                ('my_message', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp', models.CharField(default='537185', max_length=6)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
