# Generated by Django 3.0.7 on 2022-10-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='884654', max_length=6),
        ),
    ]
