# Generated by Django 3.1.6 on 2022-09-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, max_length=150)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True, max_length=150)),
                ('Address', models.CharField(blank=True, max_length=150)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
