# Generated by Django 3.1.6 on 2022-09-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_addemployeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
