# Generated by Django 3.0.7 on 2022-10-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221007_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='end',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='start',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='980346', max_length=6),
        ),
    ]
