# Generated by Django 3.0.7 on 2022-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221007_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='addagent',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='150976', max_length=6),
        ),
    ]
