# Generated by Django 3.1.6 on 2022-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='573131', max_length=6),
        ),
    ]
