# Generated by Django 3.1.6 on 2022-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220920_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployeemodel',
            name='employee_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='751348', max_length=6),
        ),
    ]
