# Generated by Django 3.1.6 on 2022-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220920_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField(max_length=7)),
                ('used_for_purpose', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='660952', max_length=6),
        ),
    ]
