# Generated by Django 3.1.6 on 2022-09-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220921_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=150)),
                ('time', models.TimeField(blank=True, max_length=150)),
                ('amount', models.IntegerField(max_length=15)),
                ('agent', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='632205', max_length=6),
        ),
    ]
