# Generated by Django 3.1.6 on 2022-09-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220921_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, max_length=150)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.IntegerField(blank=True, max_length=150)),
                ('Address', models.CharField(blank=True, max_length=150)),
                ('Country', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('agent_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='439222', max_length=6),
        ),
    ]
