# Generated by Django 3.1.6 on 2022-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220921_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addagent',
            name='Address',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='270902', max_length=6),
        ),
    ]
