# Generated by Django 3.1.6 on 2022-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220921_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='253554', max_length=6),
        ),
    ]
